version: '3'
services:
  web:
    image: gifsync_web:dev
    build:
      context: .
      dockerfile: Dockerfile_web
    env_file:
      - web.env
    ports:
      - '8000:8000'
    volumes:
      - ./gifsync:/app/gifsync
    depends_on:
      - db
  db:
    image: gifsync_db:dev
    build:
      context: .
      dockerfile: Dockerfile_db
    env_file:
      - db.env
    ports:
      - '5432:5432'
    volumes:
      - ./db_backup:/backup
