FROM python:3.11-slim-buster
RUN apt-get update && apt-get upgrade -y && apt-get install -y bash curl openssh-server gifsicle \
  && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
WORKDIR /app
COPY ./.profile.d ./pyproject.toml ./README.md ./LICENSE.txt ./gifsync /app/

RUN pip3 install .[server]
CMD exec gunicorn -b 0.0.0.0:${PORT:-8000} --workers=1 --threads=2 --worker-class=gthread gifsync:app --log-file -
