FROM python:3.8-slim-buster
MAINTAINER Carson Mullins "carsonmullins@yahoo.com"
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip3 install -r requirements.txt
COPY ./gifsync /app/gifsync
CMD exec gunicorn -b 0.0.0.0:${PORT:-8000} --log-file=- --workers=2 --threads=4 --worker-class=gthread gifsync:app
